package com.master.bedtime.parent;

import android.app.Activity;import android.os.Bundle;import android.view.Gravity;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import org.json.JSONArray;import org.json.JSONObject;
public class MainActivity extends Activity{
 private static final String MODE="selected_role";private EditText backend,child;private TextView status,codeView,childrenView;private String parentToken="";
 @Override protected void onCreate(Bundle b){super.onCreate(b);String r=getPreferences(0).getString(MODE,"");if("parent".equals(r)){parentToken=getPreferences(0).getString("parent_token","");showParent();}else if("child".equals(r))launchChild();else chooser();}
 private void chooser(){LinearLayout x=box();TextView t=new TextView(this);t.setText("BEDTIME PARENTAL\n\nWho are you?");t.setTextSize(26);t.setGravity(Gravity.CENTER);x.addView(t);Button p=new Button(this);p.setText("👨 PARENT");x.addView(p);Button c=new Button(this);c.setText("👶 CHILD");x.addView(c);p.setOnClickListener(v->{getPreferences(0).edit().putString(MODE,"parent").apply();parentToken=getPreferences(0).getString("parent_token","");showParent();});c.setOnClickListener(v->{getPreferences(0).edit().putString(MODE,"child").apply();launchChild();});setContentView(x);}
 private void launchChild(){try{startActivity(new android.content.Intent(this,com.master.bedtime.child.MainActivity.class));}catch(Exception e){chooser();}}
 private LinearLayout box(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(30,40,30,30);x.setGravity(Gravity.CENTER_HORIZONTAL);return x;}
 private void showParent(){LinearLayout root=box();TextView title=new TextView(this);title.setText("PARENT CONTROL");title.setTextSize(28);title.setGravity(Gravity.CENTER);root.addView(title);backend=new EditText(this);backend.setHint("Backend URL");backend.setText(getPreferences(0).getString("backend","https://bedtime-parental-api.itjundobal.workers.dev"));root.addView(backend);childrenView=new TextView(this);childrenView.setText("Children: none yet");root.addView(childrenView);codeView=new TextView(this);codeView.setText("No new pairing code");codeView.setTextSize(28);codeView.setGravity(Gravity.CENTER);root.addView(codeView);Button add=new Button(this);add.setText("ADD CHILD — GENERATE NEW 6-DIGIT CODE");root.addView(add);child=new EditText(this);child.setHint("Selected Child ID");root.addView(child);Button on=new Button(this);on.setText("BEDTIME ON");root.addView(on);Button off=new Button(this);off.setText("BEDTIME OFF");root.addView(off);status=new TextView(this);status.setText(parentToken.isEmpty()?"Ready — add your first Child.":"Parent account restored — ready for another Child.");root.addView(status);setContentView(root);if(!parentToken.isEmpty())poll();add.setOnClickListener(v->addChild());on.setOnClickListener(v->setBedtime(true));off.setOnClickListener(v->setBedtime(false));}
 private void addChild(){String base=backend.getText().toString().trim().replaceAll("/$","");status.setText("Generating new Child code…");new Thread(()->{try{HttpURLConnection x=(HttpURLConnection)new URL(base+"/api/pairing/create").openConnection();x.setRequestMethod("POST");x.setConnectTimeout(7000);x.setReadTimeout(7000);x.setRequestProperty("Content-Type","application/json");if(!parentToken.isEmpty())x.setRequestProperty("X-Parent-Token",parentToken);x.setDoOutput(true);try(OutputStream o=x.getOutputStream()){o.write("{}".getBytes(StandardCharsets.UTF_8));}int r=x.getResponseCode();String body=read(x,r);if(r<200||r>=300)throw new Exception(body);JSONObject d=new JSONObject(body);parentToken=d.getString("parentToken");String id=d.getString("childId"),code=d.getString("code");getPreferences(0).edit().putString("backend",base).putString("parent_token",parentToken).putString("child",id).apply();runOnUiThread(()->{child.setText(id);codeView.setText("NEW CODE: "+code);status.setText("Give this code to Child. Expires in 15 minutes.");});poll();}catch(Exception e){runOnUiThread(()->status.setText("Pairing failed: "+e.getMessage()));}}).start();}
 private void poll(){new Thread(()->{try{String base=backend.getText().toString().trim().replaceAll("/$","");HttpURLConnection x=(HttpURLConnection)new URL(base+"/api/pairing/status").openConnection();x.setRequestProperty("X-Parent-Token",parentToken);int r=x.getResponseCode();String b=read(x,r);if(r<200||r>=300)throw new Exception(b);JSONObject d=new JSONObject(b);JSONArray a=d.optJSONArray("children");StringBuilder s=new StringBuilder("Children linked: ");if(a==null||a.length()==0)s.append("none");else for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c!=null){if(i>0)s.append("\n");s.append(i+1).append(". ").append(c.optString("childId")).append(c.optBoolean("paired")?" — PAIRED ✓":" — WAITING FOR CHILD");}}runOnUiThread(()->childrenView.setText(s.toString()));}catch(Exception ignored){}}).start();}
 private void setBedtime(boolean a){String base=backend.getText().toString().trim().replaceAll("/$","");String id=child.getText().toString().trim();status.setText(a?"Sending Bedtime ON…":"Sending Bedtime OFF…");new Thread(()->{try{HttpURLConnection x=(HttpURLConnection)new URL(base+"/api/children/"+id+"/bedtime").openConnection();x.setRequestMethod("POST");x.setRequestProperty("Content-Type","application/json");x.setRequestProperty("X-Parent-Token",parentToken);x.setDoOutput(true);try(OutputStream o=x.getOutputStream()){o.write(("{\"active\":"+a+"}").getBytes(StandardCharsets.UTF_8));}int r=x.getResponseCode();runOnUiThread(()->status.setText(r>=200&&r<300?(a?"Bedtime ON ✓":"Bedtime OFF ✓"):"Server error "+r));}catch(Exception e){runOnUiThread(()->status.setText("Connection failed"));}}).start();}
 private String read(HttpURLConnection x,int c)throws Exception{BufferedReader b=new BufferedReader(new InputStreamReader(c>=400?x.getErrorStream():x.getInputStream()));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l);b.close();return s.toString();}
}