package com.master.bedtime.child;

import android.app.AlarmManager;import android.app.NotificationChannel;import android.app.NotificationManager;import android.app.PendingIntent;import android.app.Service;import android.app.admin.DevicePolicyManager;import android.content.Context;import android.content.Intent;import android.content.SharedPreferences;import android.os.Build;import android.os.IBinder;import android.os.SystemClock;import android.provider.Settings;import android.util.Log;import org.json.JSONObject;import java.io.BufferedReader;import java.io.InputStreamReader;import java.net.HttpURLConnection;import java.net.URL;

public class BedtimeMonitorService extends Service {
 private volatile boolean running; private Thread worker; private static final String CHANNEL="bedtime_monitor"; private static final String TAG="BedtimeMonitor"; private static final long POLL_INTERVAL_MS=1000L; private static final long RESTART_DELAY_MS=5000L; private Boolean lastAppliedActive=null;
 @Override public void onCreate(){super.onCreate();createChannel();Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);android.app.Notification n=new android.app.Notification.Builder(this,CHANNEL).setContentTitle("Bedtime monitor active").setContentText("Listening for parent bedtime commands").setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentIntent(pi).setOngoing(true).build();startForeground(7,n);running=true;worker=new Thread(this::pollLoop,"bedtime-poll");worker.start();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel(CHANNEL,"Bedtime Monitor",NotificationManager.IMPORTANCE_LOW));}
 private boolean isDeviceOwner(){DevicePolicyManager d=(DevicePolicyManager)getSystemService(Context.DEVICE_POLICY_SERVICE);return d!=null&&d.isDeviceOwnerApp(getPackageName());}
 private boolean setupComplete(){return getSharedPreferences("cfg",MODE_PRIVATE).getBoolean("setup_complete",false);}
 private void scheduleRestart(){if(!setupComplete())return;try{AlarmManager a=(AlarmManager)getSystemService(Context.ALARM_SERVICE);Intent r=new Intent(this,MonitorRestartReceiver.class).setAction("com.master.bedtime.child.RESTART_MONITOR");PendingIntent p=PendingIntent.getBroadcast(this,73,r,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);a.setAndAllowWhileIdle(AlarmManager.ELAPSED_REALTIME_WAKEUP,SystemClock.elapsedRealtime()+RESTART_DELAY_MS,p);}catch(Exception e){Log.e(TAG,"restart schedule failed",e);}}
 private String normalizeBackend(String value){if(value==null)return"";String raw=value.trim();while(raw.endsWith("/"))raw=raw.substring(0,raw.length()-1);if(raw.isEmpty())return"";while(raw.toLowerCase().startsWith("http://")||raw.toLowerCase().startsWith("https://"))raw=raw.toLowerCase().startsWith("https://")?raw.substring(8):raw.substring(7);return "https://"+raw;}
 private void showManagedLock(){try{startActivity(new Intent(this,BedtimeLockActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));}catch(Exception e){Log.e(TAG,"lock failed",e);}}
 private void hideManagedLock(){try{startActivity(new Intent(this,BedtimeLockActivity.class).putExtra("bedtime_off",true).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));}catch(Exception e){Log.e(TAG,"unlock failed",e);}}
 private void applyState(boolean active){if(lastAppliedActive!=null&&lastAppliedActive==active)return;if(isDeviceOwner()){BedtimeOverlay.hide(this);if(active)showManagedLock();else hideManagedLock();}else{if(active&&Settings.canDrawOverlays(this))BedtimeOverlay.show(this);if(!active)BedtimeOverlay.hide(this);}lastAppliedActive=active;}
 private void pollLoop(){while(running){HttpURLConnection c=null;try{SharedPreferences p=getSharedPreferences("cfg",MODE_PRIVATE);String base=normalizeBackend(p.getString("backend",""));String child=p.getString("child","child-001");if(!base.isEmpty()){c=(HttpURLConnection)new URL(base+"/api/children/"+child+"/bedtime").openConnection();c.setRequestMethod("GET");c.setConnectTimeout(5000);c.setReadTimeout(5000);if(c.getResponseCode()==200){StringBuilder s=new StringBuilder();try(BufferedReader b=new BufferedReader(new InputStreamReader(c.getInputStream()))){String l;while((l=b.readLine())!=null)s.append(l);}JSONObject j=new JSONObject(s.toString());boolean active=j.optBoolean("active",false);p.edit().putBoolean("last_active",active).putBoolean("allow_power_controls",j.optBoolean("allowPowerControls",false)).putLong("last_poll_ok_at",System.currentTimeMillis()).apply();applyState(active);}}}catch(Exception e){Log.e(TAG,"Poll failed: "+e.getMessage());}finally{if(c!=null)c.disconnect();}try{Thread.sleep(POLL_INTERVAL_MS);}catch(InterruptedException e){return;}}}
 @Override public int onStartCommand(Intent intent,int flags,int startId){return START_STICKY;} @Override public void onTaskRemoved(Intent rootIntent){scheduleRestart();super.onTaskRemoved(rootIntent);} @Override public void onDestroy(){running=false;if(worker!=null)worker.interrupt();scheduleRestart();super.onDestroy();} @Override public IBinder onBind(Intent intent){return null;}
}
