package com.master.bedtime.child;

import com.master.bedtime.parent.R;
import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.app.admin.DevicePolicyManager;import android.content.Intent;import android.net.Uri;import android.os.Build;import android.os.Bundle;import android.provider.Settings;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.TextView;import android.widget.Toast;
public class MainActivity extends Activity {
 private EditText backend,child;private TextView status,setupStep,deviceOwnerStatus,deviceOwnerHelp;private Button permission,start,test,restoreAccounts,releaseDeviceOwner;private DevicePolicyManager dpm;
 @Override protected void onCreate(Bundle savedInstanceState){super.onCreate(savedInstanceState);setContentView(R.layout.child_activity_main);backend=findViewById(R.id.backendUrl);child=findViewById(R.id.childId);status=findViewById(R.id.status);setupStep=findViewById(R.id.setupStep);deviceOwnerStatus=findViewById(R.id.deviceOwnerStatus);deviceOwnerHelp=findViewById(R.id.deviceOwnerHelp);Button accounts=findViewById(R.id.btnAccountsSecurity);Button cont=findViewById(R.id.btnContinueSetup);permission=findViewById(R.id.btnOverlayPermission);start=findViewById(R.id.btnStartMonitor);restoreAccounts=findViewById(R.id.btnRestoreAccounts);test=findViewById(R.id.btnTestOverlay);releaseDeviceOwner=findViewById(R.id.btnReleaseDeviceOwner);dpm=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);String saved=getSharedPreferences("cfg",MODE_PRIVATE).getString("backend","https://bedtime-parental-api.itjundobal.workers.dev");String normalized=normalizeBackend(saved);backend.setText(normalized);getSharedPreferences("cfg",MODE_PRIVATE).edit().putString("backend",normalized).apply();child.setText(getSharedPreferences("cfg",MODE_PRIVATE).getString("child","child-001"));accounts.setOnClickListener(v->showAccountPreparationReminder());cont.setOnClickListener(v->{getSharedPreferences("cfg",MODE_PRIVATE).edit().putBoolean("accounts_confirmed",true).apply();refreshSetupState();});permission.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName()))));start.setOnClickListener(v->startMonitor());restoreAccounts.setOnClickListener(v->showRestoreAccountsReminder());test.setOnClickListener(v->testBedtime());releaseDeviceOwner.setOnClickListener(v->confirmReleaseDeviceOwner());if(!getSharedPreferences("cfg",MODE_PRIVATE).getBoolean("account_reminder_seen",false))showAccountPreparationReminder();refreshSetupState();}
 @Override protected void onResume(){super.onResume();refreshSetupState();} private boolean isDeviceOwner(){return dpm!=null&&dpm.isDeviceOwnerApp(getPackageName());}
 private String normalizeBackend(String value){if(value==null)return"";String raw=value.trim();while(raw.endsWith("/"))raw=raw.substring(0,raw.length()-1);if(raw.isEmpty())return"";boolean https=raw.toLowerCase().contains("https://");while(raw.toLowerCase().startsWith("http://")||raw.toLowerCase().startsWith("https://"))raw=raw.toLowerCase().startsWith("https://")?raw.substring(8):raw.substring(7);if(raw.toLowerCase().endsWith(".workers.dev")||raw.toLowerCase().contains(".workers.dev/"))return"https://"+raw;return https?"https://"+raw:"https://"+raw;}
 private void refreshSetupState(){boolean accounts=getSharedPreferences("cfg",MODE_PRIVATE).getBoolean("accounts_confirmed",false);boolean complete=getSharedPreferences("cfg",MODE_PRIVATE).getBoolean("setup_complete",false);boolean owner=isDeviceOwner();if(!accounts){setupStep.setText("STEP 1 OF 5 — Remove saved accounts");deviceOwnerStatus.setText("Device Owner: waiting for account preparation");deviceOwnerHelp.setText("Pagkatapos alisin ang accounts, bumalik dito at pindutin ang TAPOS NA — CONTINUE SETUP.");}else if(!owner){setupStep.setText("STEP 2 OF 5 — Activate Device Owner");deviceOwnerStatus.setText("Device Owner: NOT ACTIVE");deviceOwnerHelp.setText("Ikonekta ang phone sa PC at patakbuhin:\n\nadb shell dpm set-device-owner "+getPackageName()+"/.BedtimeDeviceAdminReceiver\n\nPag success, bumalik sa app.");}else if(!complete){setupStep.setText("STEP 3 OF 5 — Pair and start monitor");deviceOwnerStatus.setText("Device Owner: ACTIVE ✓");deviceOwnerHelp.setText("Managed mode ready. Ilagay ang backend at Child ID, pagkatapos START BEDTIME MONITOR.");}else{setupStep.setText("STEP 5 OF 5 — Setup complete");deviceOwnerStatus.setText("Device Owner: ACTIVE ✓");deviceOwnerHelp.setText("Setup complete. Maaari mong palitan ang Backend URL o Child ID.");}permission.setVisibility(owner?View.GONE:View.VISIBLE);start.setEnabled(accounts&&(owner||Settings.canDrawOverlays(this)));start.setText(complete?"SAVE / RESTART BEDTIME MONITOR":"3. START BEDTIME MONITOR");restoreAccounts.setVisibility(complete?View.VISIBLE:View.GONE);test.setEnabled(accounts&&(owner||Settings.canDrawOverlays(this)));releaseDeviceOwner.setVisibility(owner?View.VISIBLE:View.GONE);if(complete)status.setText(owner?"READY — Managed Bedtime Monitor running":"READY — Fallback Bedtime Monitor running");}
 private void startMonitor(){boolean owner=isDeviceOwner();if(!owner&&!Settings.canDrawOverlays(this)){Toast.makeText(this,"Allow Display over other apps first for fallback mode.",Toast.LENGTH_LONG).show();return;}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=getPackageManager().PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},101);String b=normalizeBackend(backend.getText().toString()),c=child.getText().toString().trim();if(b.isEmpty()||c.isEmpty()){Toast.makeText(this,"Ilagay muna ang Backend URL at Child ID.",Toast.LENGTH_LONG).show();return;}backend.setText(b);boolean was=getSharedPreferences("cfg",MODE_PRIVATE).getBoolean("setup_complete",false);getSharedPreferences("cfg",MODE_PRIVATE).edit().putString("backend",b).putString("child",c).putBoolean("setup_complete",true).apply();startForegroundService(new Intent(this,BedtimeMonitorService.class));refreshSetupState();Toast.makeText(this,was?"Bedtime monitor settings saved.":"Bedtime monitor started.",Toast.LENGTH_LONG).show();if(!was)showRestoreAccountsReminder();}
 private void testBedtime(){if(isDeviceOwner()){getSharedPreferences("cfg",MODE_PRIVATE).edit().putBoolean("last_active",true).apply();startActivity(new Intent(this,BedtimeLockActivity.class));}else if(Settings.canDrawOverlays(this))BedtimeOverlay.show(this);else Toast.makeText(this,"Allow overlay permission first.",Toast.LENGTH_LONG).show();}
 private void confirmReleaseDeviceOwner(){if(!isDeviceOwner()){refreshSetupState();return;}new AlertDialog.Builder(this).setTitle("TEST ONLY — Release Device Owner?").setMessage("Tatanggalin nito ang Device Owner role para ma-uninstall o ma-reprovision ang test device.").setNegativeButton("CANCEL",null).setPositiveButton("RELEASE DEVICE OWNER",(d,w)->releaseDeviceOwnerForTesting()).show();}
 @SuppressWarnings("deprecation")private void releaseDeviceOwnerForTesting(){try{getSharedPreferences("cfg",MODE_PRIVATE).edit().putBoolean("last_active",false).putBoolean("setup_complete",false).apply();stopService(new Intent(this,BedtimeMonitorService.class));dpm.clearDeviceOwnerApp(getPackageName());Toast.makeText(this,"Device Owner released for testing.",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Release failed: "+e.getClass().getSimpleName(),Toast.LENGTH_LONG).show();}refreshSetupState();}
 private void showAccountPreparationReminder(){new AlertDialog.Builder(this).setTitle("Bago tayo magsimula").setMessage("Para tuloy-tuloy ang Device Owner setup, alisin muna ang mga naka-save na account sa device. Siguraduhing alam ninyo ang login details bago alisin ang mga ito. Maaari silang ibalik pagkatapos ng setup.").setNegativeButton("Hindi muna",null).setPositiveButton("OKAY, PUNTA SA ACCOUNTS",(d,w)->{getSharedPreferences("cfg",MODE_PRIVATE).edit().putBoolean("account_reminder_seen",true).apply();openAccountsSettings();}).show();}
 private void showRestoreAccountsReminder(){new AlertDialog.Builder(this).setTitle("Setup complete").setMessage("Tapos na ang Bedtime setup. Maaari nang ibalik o idagdag muli ang mga account.").setNegativeButton("Mamaya",null).setPositiveButton("PUNTA SA ACCOUNTS",(d,w)->openAccountsSettings()).show();}
 private void openAccountsSettings(){try{startActivity(new Intent(Settings.ACTION_SYNC_SETTINGS));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}}
}
