name = "bedtime-parental-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[durable_objects.bindings]]
name = "BEDTIME_STATE_DO"
class_name = "BedtimeState"

[[migrations]]
tag = "v1-durable-bedtime-state"
new_sqlite_classes = [ "BedtimeState" ]
