// Pairing API redeploy marker: keep Parent -> Generate Code endpoint live.
export class BedtimeState {
  constructor(state, env) {
    this.state = state;
    this.env = env;
  }

  async fetch() {
    return new Response('BedtimeState Durable Object is preserved.', { status: 200 });
  }
}

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-parent-key,x-parent-token,x-child-token'}})}
function randomToken(bytes=24){const b=new Uint8Array(bytes);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
function randomCode(){const b=new Uint32Array(1);crypto.getRandomValues(b);return String(b[0]%1000000).padStart(6,'0')}
function dashboard(){return new Response(`<!doctype html><html><body style="font-family:Arial;background:#0f172a;color:white;padding:30px"><h1>🌙 Bedtime Parent Control</h1><button onclick="add()">ADD CHILD — GENERATE NEW 6-DIGIT CODE</button><pre id="out"></pre><input id="id" placeholder="Selected Child ID"><button onclick="bed(true)">BEDTIME ON</button><button onclick="bed(false)">BEDTIME OFF</button><script>let token=localStorage.parentToken||'';async function add(){let h={'content-type':'application/json'};if(token)h['x-parent-token']=token;let r=await fetch('/api/pairing/create',{method:'POST',headers:h,body:'{}'}),d=await r.json();if(!r.ok)return out.textContent=d.error;token=d.parentToken;localStorage.parentToken=token;id.value=d.childId;out.textContent='NEW CHILD CODE: '+d.code+'\\nCHILD ID: '+d.childId+'\\nExpires in 15 minutes.'}async function bed(a){let r=await fetch('/api/children/'+encodeURIComponent(id.value)+'/bedtime',{method:'POST',headers:{'content-type':'application/json','x-parent-token':token},body:JSON.stringify({active:a})});out.textContent=await r.text()}</script></body></html>`,{headers:{'content-type':'text/html; charset=utf-8'}})}
export default{async fetch(request,env){if(request.method==='OPTIONS')return json({ok:true});const u=new URL(request.url);if(u.pathname==='/'&&request.method==='GET')return dashboard();if(u.pathname==='/health')return json({ok:true,service:'bedtime-parental-worker'});
if(u.pathname==='/api/pairing/create'&&request.method==='POST'){let parentToken=request.headers.get('x-parent-token')||'';let parent=parentToken?await env.BEDTIME_STATE.get('parent:'+parentToken,{type:'json'}):null;if(!parent){parentToken=randomToken(24);parent={children:[]}}const code=randomCode(),childId='child-'+randomToken(8).slice(0,12);const children=Array.isArray(parent.children)?parent.children:[];children.push(childId);await env.BEDTIME_STATE.put('paircode:'+code,JSON.stringify({parentToken,childId}),{expirationTtl:900});await env.BEDTIME_STATE.put('parent:'+parentToken,JSON.stringify({childId,children}),{expirationTtl:31536000});return json({ok:true,code,childId,parentToken,expiresIn:900})}
if(u.pathname==='/api/pairing/redeem'&&request.method==='POST'){let b;try{b=await request.json()}catch{return json({error:'invalid json'},400)}const code=String(b?.code||'').trim();if(!/^\d{6}$/.test(code))return json({error:'pairing code must be 6 digits'},400);const pair=await env.BEDTIME_STATE.get('paircode:'+code,{type:'json'});if(!pair?.parentToken)return json({error:'pairing code expired or invalid'},404);const childToken=randomToken(24);await env.BEDTIME_STATE.put('child:'+pair.childId,JSON.stringify({childToken,parentToken:pair.parentToken}),{expirationTtl:31536000});await env.BEDTIME_STATE.delete('paircode:'+code);return json({ok:true,childId:pair.childId,childToken,paired:true})}
if(u.pathname==='/api/pairing/status'&&request.method==='GET'){const pt=request.headers.get('x-parent-token')||'';const p=await env.BEDTIME_STATE.get('parent:'+pt,{type:'json'});if(!p)return json({error:'invalid parent token'},401);const ids=Array.isArray(p.children)?p.children:[];const children=[];for(const id of ids){const r=await env.BEDTIME_STATE.get('child:'+id,{type:'json'});children.push({childId:id,paired:!!r?.childToken})}return json({ok:true,children})}
const m=u.pathname.match(/^\/api\/children\/([^/]+)\/bedtime$/);if(!m)return json({error:'not found'},404);const childId=decodeURIComponent(m[1]);if(!/^[A-Za-z0-9._-]{1,80}$/.test(childId))return json({error:'invalid childId'},400);const key='bedtime:'+childId;
if(request.method==='GET'){const cr=await env.BEDTIME_STATE.get('child:'+childId,{type:'json'});if(cr?.childToken&&(request.headers.get('x-child-token')||'')!==cr.childToken)return json({error:'unauthorized'},401);const s=await env.BEDTIME_STATE.get(key,{type:'json'});return json({childId,active:s?.active===true,allowPowerControls:s?.allowPowerControls===true,updatedAt:s?.updatedAt||null})}
if(request.method==='POST'){let auth=false;const pt=request.headers.get('x-parent-token')||'';if(pt){const p=await env.BEDTIME_STATE.get('parent:'+pt,{type:'json'});auth=Array.isArray(p?.children)?p.children.includes(childId):p?.childId===childId}if(!auth&&env.PARENT_API_KEY)auth=(request.headers.get('x-parent-key')||'')===env.PARENT_API_KEY;if(!auth&&env.PARENT_API_KEY)return json({error:'unauthorized'},401);let b;try{b=await request.json()}catch{return json({error:'invalid json'},400)}if(typeof b?.active!=='boolean')return json({error:'active must be boolean'},400);const prev=await env.BEDTIME_STATE.get(key,{type:'json'});const state={active:b.active,allowPowerControls:b.allowPowerControls===true||(b.allowPowerControls===undefined&&prev?.allowPowerControls===true),updatedAt:new Date().toISOString()};await env.BEDTIME_STATE.put(key,JSON.stringify(state));return json({ok:true,childId,...state})}return json({error:'method not allowed'},405)}}