// Pairing API: Child -> Generate Code -> Parent Redeem -> Child receives token.
export class BedtimeState {
  constructor(state, env) {
    this.state = state;
    this.env = env;
  }

  async fetch() {
    return new Response('BedtimeState Durable Object is preserved.', { status: 200 });
  }
}

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-parent-key,x-parent-token,x-child-token'}})}
function randomToken(bytes=24){const b=new Uint8Array(bytes);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
function randomCode(){const b=new Uint32Array(1);crypto.getRandomValues(b);return String(b[0]%1000000).padStart(6,'0')}
function dashboard(){return new Response(`<!doctype html><html><body style="font-family:Arial;background:#0f172a;color:white;padding:30px"><h1>🌙 Bedtime Parent Control</h1><p>Enter the 6-digit code shown on the Child device.</p><input id="code" inputmode="numeric" maxlength="6" placeholder="Child pairing code"><button onclick="add()">ADD CHILD</button><pre id="out"></pre><input id="id" placeholder="Selected Child ID"><button onclick="bed(true)">BEDTIME ON</button><button onclick="bed(false)">BEDTIME OFF</button><script>let token=localStorage.parentToken||'';async function init(){if(token)return;let r=await fetch('/api/pairing/parent',{method:'POST',headers:{'content-type':'application/json'}}),d=await r.json();if(r.ok){token=d.parentToken;localStorage.parentToken=token}}async function add(){await init();let h={'content-type':'application/json','cache-control':'no-cache','x-parent-token':token};let r=await fetch('/api/pairing/redeem',{method:'POST',headers:h,body:JSON.stringify({code:code.value})}),d=await r.json();if(!r.ok)return out.textContent=d.error;id.value=d.childId;out.textContent='CHILD PAIRED ✓\\nCHILD ID: '+d.childId}async function bed(a){await init();let r=await fetch('/api/children/'+encodeURIComponent(id.value)+'/bedtime',{method:'POST',headers:{'content-type':'application/json','x-parent-token':token},body:JSON.stringify({active:a})});out.textContent=await r.text()}init()</script></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})}
export default{async fetch(request,env){if(request.method==='OPTIONS')return json({ok:true});const u=new URL(request.url);if(u.pathname==='/'&&request.method==='GET')return dashboard();if(u.pathname==='/health')return json({ok:true,service:'bedtime-parental-worker'});
if(u.pathname==='/api/pairing/parent'&&request.method==='POST'){const parentToken=randomToken(24);await env.BEDTIME_STATE.put('parent:'+parentToken,JSON.stringify({children:[]}),{expirationTtl:31536000});return json({ok:true,parentToken})}
if(u.pathname==='/api/pairing/child/create'&&request.method==='POST'){let b={};try{b=await request.json()}catch{}let requestedChildId=String(b?.childId||'').trim();let childId=(requestedChildId&&requestedChildId!=='child-001'&&/^[A-Za-z0-9._-]{1,80}$/.test(requestedChildId))?requestedChildId:'';if(childId&&await env.BEDTIME_STATE.get('child:'+childId,{type:'json'}))childId='';if(!childId)childId='child-'+randomToken(8).slice(0,12);const code=randomCode();await env.BEDTIME_STATE.put('paircode:'+code,JSON.stringify({childId,consumed:false}),{expirationTtl:900});await env.BEDTIME_STATE.put('child:'+childId,JSON.stringify({pairingCode:code,paired:false}),{expirationTtl:900});return json({ok:true,code,childId,expiresIn:900})}
if(u.pathname==='/api/pairing/redeem'&&request.method==='POST'){const parentToken=request.headers.get('x-parent-token')||'';const parent=await env.BEDTIME_STATE.get('parent:'+parentToken,{type:'json'});if(!parent)return json({error:'invalid parent token'},401);let b;try{b=await request.json()}catch{return json({error:'invalid json'},400)}const code=String(b?.code||'').trim();if(!/^\d{6}$/.test(code))return json({error:'pairing code must be 6 digits'},400);const pair=await env.BEDTIME_STATE.get('paircode:'+code,{type:'json'});if(!pair?.childId)return json({error:'pairing code expired or invalid'},404);if(pair.consumed)return json({error:'pairing code already used'},409);const childToken=randomToken(24);await env.BEDTIME_STATE.put('child:'+pair.childId,JSON.stringify({childToken,parentToken,paired:true,pairingCode:code,pairedAt:new Date().toISOString()}),{expirationTtl:31536000});const children=Array.isArray(parent.children)?parent.children:[];if(!children.includes(pair.childId))children.push(pair.childId);await env.BEDTIME_STATE.put('parent:'+parentToken,JSON.stringify({children}),{expirationTtl:31536000});await env.BEDTIME_STATE.put('paircode:'+code,JSON.stringify({childId:pair.childId,consumed:true}),{expirationTtl:900});return json({ok:true,childId:pair.childId,childToken,paired:true})}
if(u.pathname==='/api/pairing/child/status'&&request.method==='GET'){const code=String(u.searchParams.get('code')||'').trim();if(!/^\d{6}$/.test(code))return json({error:'pairing code must be 6 digits'},400);const pair=await env.BEDTIME_STATE.get('paircode:'+code,{type:'json'});if(!pair?.childId)return json({ok:true,paired:false});const child=await env.BEDTIME_STATE.get('child:'+pair.childId,{type:'json'});return json({ok:true,paired:!!child?.paired,childId:pair.childId,childToken:child?.childToken||null})}
if(u.pathname==='/api/pairing/status'&&request.method==='GET'){const pt=request.headers.get('x-parent-token')||'';const p=await env.BEDTIME_STATE.get('parent:'+pt,{type:'json'});if(!p)return json({error:'invalid parent token'},401);const ids=Array.isArray(p.children)?p.children:[];const children=[];for(const id of ids){const r=await env.BEDTIME_STATE.get('child:'+id,{type:'json'});children.push({childId:id,paired:!!r?.childToken})}return json({ok:true,children})}
const m=u.pathname.match(/^\/api\/children\/([^/]+)\/bedtime$/);if(!m)return json({error:'not found'},404);const childId=decodeURIComponent(m[1]);if(!/^[A-Za-z0-9._-]{1,80}$/.test(childId))return json({error:'invalid childId'},400);const key='bedtime:'+childId;
if(request.method==='GET'){const cr=await env.BEDTIME_STATE.get('child:'+childId,{type:'json'});if(cr?.childToken&&(request.headers.get('x-child-token')||'')!==cr.childToken)return json({error:'unauthorized'},401);const s=await env.BEDTIME_STATE.get(key,{type:'json'});return json({childId,active:s?.active===true,allowPowerControls:s?.allowPowerControls===true,updatedAt:s?.updatedAt||null})}
if(request.method==='POST'){let auth=false;const pt=request.headers.get('x-parent-token')||'';if(pt){const p=await env.BEDTIME_STATE.get('parent:'+pt,{type:'json'});auth=Array.isArray(p?.children)?p.children.some(x=>(typeof x==='string'?x:x?.childId)===childId):p?.childId===childId}if(!auth&&env.PARENT_API_KEY)auth=(request.headers.get('x-parent-key')||'')===env.PARENT_API_KEY;if(!auth&&env.PARENT_API_KEY)return json({error:'unauthorized'},401);let b;try{b=await request.json()}catch{return json({error:'invalid json'},400)}if(typeof b?.active!=='boolean')return json({error:'active must be boolean'},400);const prev=await env.BEDTIME_STATE.get(key,{type:'json'});const state={active:b.active,allowPowerControls:b.allowPowerControls===true||(b.allowPowerControls===undefined&&prev?.allowPowerControls===true),updatedAt:new Date().toISOString()};await env.BEDTIME_STATE.put(key,JSON.stringify(state));return json({ok:true,childId,...state})}return json({error:'method not allowed'},405)}}