function json(data, status = 200) {
  return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-allow-headers': 'content-type,x-parent-key,x-parent-token,x-child-token' } });
}
function randomToken(bytes = 24) { const b = new Uint8Array(bytes); crypto.getRandomValues(b); return Array.from(b, x => x.toString(16).padStart(2, '0')).join(''); }
function randomCode() { const b = new Uint32Array(1); crypto.getRandomValues(b); return String(b[0] % 1000000).padStart(6, '0'); }
function dashboard() {
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bedtime Parent Control</title><style>body{font-family:Arial;background:#0f172a;color:#fff;margin:0;min-height:100vh;display:grid;place-items:center}.card{width:min(92vw,520px);background:#111827;padding:28px;border-radius:22px}button,input{width:100%;box-sizing:border-box;padding:14px;margin-top:10px;border-radius:12px;font-size:16px}button{font-weight:700;border:0}.pair{background:#059669;color:white}.on{background:#7c3aed;color:white}.off{background:#334155;color:white}.code{font-size:36px;letter-spacing:8px;text-align:center;margin:16px 0}.child{padding:12px;margin-top:8px;background:#0b1220;border-radius:10px}</style></head><body><main class="card"><h1>🌙 Bedtime Control</h1><p>Parent web dashboard</p><button class="pair" onclick="addChild()">ADD CHILD — GENERATE NEW 6-DIGIT CODE</button><div id="code"></div><div id="children"></div><label>Selected Child ID</label><input id="child" value="child-001"><div><button class="on" onclick="setBedtime(true)">BEDTIME ON</button><button class="off" onclick="setBedtime(false)">BEDTIME OFF</button></div><p id="status">Ready</p></main><script>
let token=localStorage.getItem('parentToken')||'';let kids=JSON.parse(localStorage.getItem('children')||'[]');const child=document.getElementById('child');const status=document.getElementById('status');
function render(){document.getElementById('children').innerHTML=kids.map((k,i)=>'<div class="child"><b>Child '+(i+1)+'</b><br>'+k.childId+' — '+(k.paired?'PAIRED ✓':'WAITING…')+'</div>').join('');}
async function addChild(){status.textContent='Generating new secure pairing code…';try{const r=await fetch('/api/pairing/create',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw Error(d.error||r.status);token=d.parentToken;localStorage.setItem('parentToken',token);kids.push({childId:d.childId,paired:false});localStorage.setItem('children',JSON.stringify(kids));child.value=d.childId;document.getElementById('code').innerHTML='<div>Enter this code on the Child phone:</div><div class="code">'+d.code+'</div><div>Expires in 15 minutes.</div>';status.textContent='Waiting for Child to pair…';render();poll();}catch(e){status.textContent='Pairing error: '+e.message;}}
async function poll(){if(!token)return;try{const r=await fetch('/api/pairing/status',{headers:{'x-parent-token':token}});if(r.ok){const d=await r.json();kids=d.children||kids;localStorage.setItem('children',JSON.stringify(kids));render();if(kids.some(k=>k.paired))status.textContent='Child pairing status updated ✓';}}catch(e){}setTimeout(poll,3000)}
async function setBedtime(active){const id=child.value.trim();if(!id)return;status.textContent=active?'Sending Bedtime ON…':'Sending Bedtime OFF…';try{const h={'content-type':'application/json'};if(token)h['x-parent-token']=token;const r=await fetch('/api/children/'+encodeURIComponent(id)+'/bedtime',{method:'POST',headers:h,body:JSON.stringify({active})});const d=await r.json();status.textContent=r.ok?(active?'🌙 Bedtime is ON':'✓ Bedtime is OFF'):(d.error||'Server error');}catch(e){status.textContent='Connection failed';}}
render();poll();</script></body></html>`;
  return new Response(html, {headers:{'content-type':'text/html; charset=utf-8'}});
}
export default { async fetch(request, env) {
  if(request.method==='OPTIONS')return json({ok:true}); const url=new URL(request.url);
  if(url.pathname==='/'&&request.method==='GET')return dashboard(); if(url.pathname==='/health'&&request.method==='GET')return json({ok:true,service:'bedtime-parental-worker'});
  if(url.pathname==='/api/pairing/create'&&request.method==='POST'){const code=randomCode(),parentToken=randomToken(24),childId='child-'+randomToken(8).slice(0,12);await env.BEDTIME_STATE.put('paircode:'+code,JSON.stringify({parentToken,childId}),{expirationTtl:900});await env.BEDTIME_STATE.put('parent:'+parentToken,JSON.stringify({childId,children:[childId]}),{expirationTtl:31536000});return json({ok:true,code,childId,parentToken,expiresIn:900});}
  if(url.pathname==='/api/pairing/redeem'&&request.method==='POST'){let body;try{body=await request.json()}catch{return json({error:'invalid json'},400)}const code=String(body?.code||'').trim();if(!/^\d{6}$/.test(code))return json({error:'pairing code must be 6 digits'},400);const pair=await env.BEDTIME_STATE.get('paircode:'+code,{type:'json'});if(!pair?.parentToken||!pair?.childId)return json({error:'pairing code expired or invalid'},404);const childToken=randomToken(24);await env.BEDTIME_STATE.put('child:'+pair.childId,JSON.stringify({childToken,parentToken:pair.parentToken}),{expirationTtl:31536000});const pk='parent:'+pair.parentToken;const parent=await env.BEDTIME_STATE.get(pk,{type:'json'})||{children:[]};const children=Array.isArray(parent.children)?parent.children:[];if(!children.includes(pair.childId))children.push(pair.childId);await env.BEDTIME_STATE.put(pk,JSON.stringify({...parent,childId:pair.childId,children}),{expirationTtl:31536000});await env.BEDTIME_STATE.delete('paircode:'+code);return json({ok:true,childId:pair.childId,childToken,paired:true});}
  if(url.pathname==='/api/pairing/status'&&request.method==='GET'){const pt=request.headers.get('x-parent-token')||'';if(!pt)return json({error:'missing parent token'},401);const p=await env.BEDTIME_STATE.get('parent:'+pt,{type:'json'});if(!p)return json({error:'invalid parent token'},401);const ids=Array.isArray(p.children)?p.children:(p.childId?[p.childId]:[]);const children=[];for(const id of ids){const rec=await env.BEDTIME_STATE.get('child:'+id,{type:'json'});children.push({childId:id,paired:!!rec?.childToken});}return json({ok:true,children});}
  const match=url.pathname.match(/^\/api\/children\/([^/]+)\/bedtime$/);if(!match)return json({error:'not found'},404);const childId=decodeURIComponent(match[1]);if(!/^[A-Za-z0-9._-]{1,80}$/.test(childId))return json({error:'invalid childId'},400);const key='bedtime:'+childId;
  if(request.method==='GET'){const cr=await env.BEDTIME_STATE.get('child:'+childId,{type:'json'});if(cr?.childToken&&(request.headers.get('x-child-token')||'')!==cr.childToken)return json({error:'unauthorized'},401);const s=await env.BEDTIME_STATE.get(key,{type:'json'});return json({childId,active:s?.active===true,allowPowerControls:s?.allowPowerControls===true,updatedAt:s?.updatedAt||null});}
  if(request.method==='POST'){let auth=false;const pt=request.headers.get('x-parent-token')||'';if(pt){const p=await env.BEDTIME_STATE.get('parent:'+pt,{type:'json'});const ids=Array.isArray(p?.children)?p.children:(p?.childId?[p.childId]:[]);auth=ids.includes(childId);}if(!auth&&env.PARENT_API_KEY)auth=(request.headers.get('x-parent-key')||'')===env.PARENT_API_KEY;if(!auth&&env.PARENT_API_KEY)return json({error:'unauthorized'},401);let body;try{body=await request.json()}catch{return json({error:'invalid json'},400)}if(typeof body?.active!=='boolean')return json({error:'active must be boolean'},400);const prev=await env.BEDTIME_STATE.get(key,{type:'json'});const state={active:body.active,allowPowerControls:body.allowPowerControls===true||(body.allowPowerControls===undefined&&prev?.allowPowerControls===true),updatedAt:new Date().toISOString()};await env.BEDTIME_STATE.put(key,JSON.stringify(state));return json({ok:true,childId,...state});}
  return json({error:'method not allowed'},405);
}};